import type { Metadata } from "next";
import ClientLayout from "@/lib/ThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "[Admin] Lò luyện Online",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",     // favicon chính
    shortcut: "/favicon.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      
      <body className="antialiased">
        <ClientLayout>{children}</ClientLayout>
      </body>
      
    </html>
  );
}
