import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "../../lib/ThemeProvider";
import localFont from "next/font/local";

const inter = localFont({
  src: [
    { path: "../assets/Inter_18pt-Regular.ttf", weight: "400" },
    { path: "../assets/Inter_18pt-Medium.ttf", weight: "500" },
    { path: "../assets/Inter_18pt-SemiBold.ttf", weight: "600" },
  ],
  variable: "--font-body",
  display: "swap",
});

const robotoSlab = localFont({
  src: [
    { path: "../assets/RobotoSlab-Regular.ttf", weight: "400" },
    { path: "../assets/RobotoSlab-Medium.ttf", weight: "500" },
    { path: "../assets/RobotoSlab-Bold.ttf", weight: "700" },
  ],
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lò luyện Online",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="vi"
      className={`${robotoSlab.variable} ${inter.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased font-body bg-white text-black">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
